### ISSUE TITLE
Building the program and lists of packages

### ISSUE THREAD

**Issue by slavmetal** [msokalski/ascii-patrol#1]
Hi! It would be actually great to provide some basic instructions for building the program and provide the list of packages that are already in some Linux distro's repositories (so people could install it in one command). 

Here's the package I created for Arch Linux users: https://aur.archlinux.org/packages/ascii-patrol-git/

**Comment by msokalski** [comment]
Hi @SlavMetal 
First of all, thanks for adding it to arch packages! 
(I didn't know debian and arch have compatible binaries)

## Packages:
I have compiled ascii-patrol for debian x64 compatible systems only (the one you have linked), and as I am no-expert in linux packages I didn't make any 'official' packages at all  :(

## Building is very simple (assuming we have git and g++):
```
# clone sources repo
git clone https://github.com/msokalski/ascii-patrol.git

# enter sources directory
cd ascii-patrol

# enable execution of build.sh and run.sh scripts
chmod +x *.sh

# install required packages
sudo apt-get install libx11-dev libpulse-dev

# invoke compilation
./build.sh
```
## Running
Ascii Patrol uses curl to communicate with hi-score server (ascii-patrol.com)
So optionally let's install it if needed.
`sudo apt-get install curl`

Finally let's piu-piu !
`./asciipat`
or
`./run.sh`

## Problems?
no sound? -> install / start pulseaudio
weird colors? -> try another terminal emulator or just run from raw console (ctrl-alt-F1 or so)
poor font look> -> try to change it in your terminal or in case of raw console use setfont
keyboard doesn't work? -> try another terminal emulator or just run from raw console (ctrl-alt-F1 or so)
no hi-scores table? -> install curl

**Comment by slavmetal** [comment]
Well, Arch and Debian packages are not compatible out-of-the-box, but you can use [debtap](https://github.com/helixarch/debtap) for that. Actually in my package I don't use binary, it compiles every time from sources (just like you mentioned in your reply). 

Thanks for the provided info! And that's what I meant, it would be really nice to show it in the **README.md** so users could see these instructions and small FAQ when they enter project's page on GiHub.  :smiley:

**Comment by msokalski** [comment]
Thanks, just commited into README.md

**Comment by slavmetal** [comment]
Thank you so much! And by the way, you could list my package for Arch so users could install it just in one command.

**Comment by msokalski** [comment]
Sure thing, done and upvoted ;)
