### ISSUE TITLE
Doesn't render correctly through secure shell.

### ISSUE THREAD

**Issue by GeriatricJacob** [msokalski/ascii-patrol#10]
When I attempt to play ascii-patrol over ssh I get this:
![image](https://user-images.githubusercontent.com/16343789/53703016-bff41780-3e58-11e9-9615-2205514fb7a5.png)
I would call this a bug.

**Comment by msokalski** [comment]
Hmm, what terminal you have (on the client side)?
Could you try different one?

**Comment by msokalski** [comment]
Is it still an issue? In order to solve it I'd need some details: what is host OS, what is client OS and what terminal app is it running. I'd appreciate any additional details narrowing the problem.

**Comment by GeriatricJacob** [comment]
I tried a new terminal client and it worked fine.

**Comment by msokalski** [comment]
Oh thanks! Don't mind me asking what was the problematic terminal?
