### ISSUE TITLE
Aborted (core dumped)

### ISSUE THREAD

**Issue by marcinzelent** [msokalski/ascii-patrol#11]
This error shows up straight after it starts to draw mountains.

```
double free or corruption (out)                                        
Aborted (core dumped)
```

I was running the prebuilt version for Linux x64. I've tried compiling it myself and the same error appeared.

I'm using Ubuntu 18.10 with KDE. Tried to run it with Konsole, XTerm, and TTY. Same problem in all of them.

**Comment by msokalski** [comment]
Hi Marcin, thanks for reporting it.
Seams to be an ufo issue right now. Any chance you could narrow the problem?
- ideally, by providing stack backtrace from your own build where crash occurs
- you could also try stopping pulse audio server, just to check if it happens in graphics or sound thread.

**Comment by nov3o** [comment]
I have the same problem. Ubuntu 18.04. Downloaded from Ubuntu Software. Default DE. The same result while running as root. Are there any crash log files? When pulseaudio is running, ascii-partol makes one sound, after which crashes
![Screenshot from 2019-03-09 23-41-46](https://user-images.githubusercontent.com/31302079/54077124-6743d500-42c5-11e9-8c02-e18bc1eaa75a.png)
![Screenshot from 2019-03-09 23-47-25](https://user-images.githubusercontent.com/31302079/54077164-d4f00100-42c5-11e9-9acf-a9b501a8c596.png)
![image](https://user-images.githubusercontent.com/31302079/54077229-b9392a80-42c6-11e9-9ba2-d0c6ce95e247.png)

**Comment by msokalski** [comment]
Guys, looks like I have similar problem with new curl. Try uninstalling it (temporarily)
`sudo apt-get remove curl`
Plase confirm if it helps.
After then install it back
`sudo apt-get install curl`
I appreciate your feedback very much.

**Comment by msokalski** [comment]
Ok, the real problem was my server http -> https redirection!
I've fixed it, does it run now with curl?

**Comment by nov3o** [comment]
I already had installed curl. I restarted pulseaudio. After reboot everything is fine. autospawn in pulse config was set to "no". When error occured, line with auatospawn was commented

**Comment by msokalski** [comment]
I'm glad to hear it runs now. 
Thanks for your help!
