### ISSUE TITLE
Doesn't work with xfce4-terminal

### ISSUE THREAD

**Issue by goberghen** [msokalski/ascii-patrol#2]
Debian unstable
xfce4-terminal, version 0.8.6-1
libvte-2.91-0, version 0.50.2-3

-----
Keyboard input doesn't work at all.

**Comment by goberghen** [comment]
UPD: Managed to run it with `DISPLAY= ./asciipat` (note the whitespace after `DISPLAY=`, we're unsetting the variable).
But it is a dirty workaround.

**Comment by msokalski** [comment]
Looks like it is not possible to hook key presses on such x11 config :( I'll look into it soon but best way of running AP is from TTY (ctrl+Fn), and even better without piped process between AP and TTY (like MC or so).

Good to know disabling X11 works, thanks :)

**Comment by goberghen** [comment]
BTW, it works in [st](https://st.suckless.org/). Maybe it's just an incompatibility with VTE-based terminal emulators?

**Comment by msokalski** [comment]
Right, confirmed that termit, terminator & gnome-terminal (all vte based) don't have kbd input, while st and xterm do. Great finding - thanks, still need to find out why ;)

**Comment by msokalski** [comment]
@goberghen Could you please verify if x11-kbd-fix branch works for you? 
Should I provide you the binaries or you are able to build it on your own?
Thx

**Comment by goberghen** [comment]
@msokalski, built it. Yes, it works now, **but** I found a strange little bug. When I launch the game and then open a new tab in the same terminal window, the game starts accepting input from this new tab too while I'm typing.
Nothing serious, but it's a bug.

**Comment by msokalski** [comment]
There is no other way to do it. AP listens to keyboard events sent to its terminal window, it can't detect if / which terminal's tab is currently active. This is the good security reason (in X11) to open each terminal in separate window. Note, I could easily steal typed sudo/ssh password and curl it to some server. SCARY!

Thank you so much for your help.

**Comment by goberghen** [comment]
Thank you.

**Comment by msokalski** [comment]
Btw, nice score!
> #30 goberghen 100567 2018-01-22 15:32:06
