### ISSUE TITLE
Unreadable name in the dialogs

### ISSUE THREAD

**Issue by slavmetal** [msokalski/ascii-patrol#4]
Player's name is unreadable in dialogs. So probably it would be great to use white color, just like with the Commander. 

![screenshot_20180209_150628](https://user-images.githubusercontent.com/17832892/36031589-868ceee2-0dab-11e8-8bfe-160d084ff657.png)

**Comment by msokalski** [comment]
Looks like your terminal has some non ANSI/VGA palette set. Note that even their 'black' is not black!
I don't know which terminal it is but hopefully you can configure it to use 'non-altered' ANSI palette somewhere in their settings. Other than than I can only suggest using another vt like linux ctrl+alt+f1.
It is not possible for the game to change terminal's palette, but let me know if you was able to set it up somehow.

Below how it should look like
![untitled-2](https://user-images.githubusercontent.com/14288504/36035361-e8174896-0db6-11e8-8ff5-6409a6acb960.png)

**Comment by slavmetal** [comment]
Oh yeah, I use custom color scheme in the Konsole terminal and I didn't expect this scheme to show two different colors as almost the one. Without this color scheme everything works like a charm, thank you!
