### ISSUE TITLE
Docker version

### ISSUE THREAD

**Issue by andrius** [msokalski/ascii-patrol#5]
Hello,

I've dockerized game. Easy to try for anyone!  

https://github.com/andrius/ascii-patrol

**Comment by msokalski** [comment]
That's cool, thanks. Unfortunately I'm completely new to the docker, and obviously I failed to run it. (tried on Windows 10 host with both Linux / Windows containers). Below is where I've stucked:

Trying to run directly without running container:
<pre>
>docker exec -ti --rm andrius/ascii-patorl
unknown flag: --rm
See 'docker exec --help'.
</pre>

Trying to start container first...
<pre>
>docker run --name ubuntu_bash --rm -i -t ubuntu bash
Unable to find image 'ubuntu:latest' locally
latest: Pulling from library/ubuntu
22dc81ace0ea: Pull complete
1a8b3c87dba3: Pull complete
91390a1c435a: Pull complete
07844b14977e: Pull complete
b78396653dae: Pull complete
Digest: sha256:e348fbbea0e0a0e73ab0370de151e7800684445c509d46195aef73e090a49bd6
Status: Downloaded newer image for ubuntu:latest
root@bc3e4c5d5225:/# docker exec -ti --rm andrius/ascii-patorl
bash: docker: command not found
</pre>

Any help, please?

**Comment by andrius** [comment]
sorry, typo. `docker run`, not `docker exec`

You don't need to run game within ubuntu on docker (which you have started successfully)

just type `docker run -ti --rm andrius/ascii-patorl`

**Comment by msokalski** [comment]
Do I need to sign up for some docker's repository credentials? Now I have this:
<pre>
>docker run -ti --rm andrius/ascii-patorl
Unable to find image 'andrius/ascii-patorl:latest' locally
docker: Error response from daemon: pull access denied for andrius/ascii-patorl, repository does not exist or may require 'docker login'.
See 'docker run --help'.
</pre>

**Comment by slavmetal** [comment]
@msokalski There's a typo in the repository name, the command actually should be like this: 
```docker run -ti --rm andrius/ascii-patrol```

**Comment by msokalski** [comment]
Thanks SlavMetal! it worked ... but runs terribly slow and in B/W only, quite disappointing hehe.

**Comment by andrius** [comment]
it depends on terminal settings and it fast on Mac

https://asciinema.org/a/oi2g2lKX5b4oBJ4h9e8kt8BjW

**Comment by msokalski** [comment]
@andrius OMG, performance is even worse on Mac (but in color!)
Easier way to try the game is to play right in the browser I guess: http://ascii-patrol.com/area51/ascii-patrol-html5.html
